steps:
  # Build the Go binary.
  - name: 'gcr.io/cloud-builders/go'
    args: ['mod', 'download']
    env: ['GO111MODULE=on']
  # Run the tests.
  - name: 'gcr.io/cloud-builders/go'
    args: ['test', './...']
    env: ['GO111MODULE=on']
  - name: 'gcr.io/cloud-builders/go'
    args: ['build', '-o', 'server']
    env: ['GO111MODULE=on']
  # Build the production image.
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--tag=gcr.io/$PROJECT_ID/helloworld',
      '--build-arg=PORT=8080',
      '--build-arg=NAME=World',
      '--file=Dockerfile-alpine',
      '.'
    ]
  # Push the production image to Container Registry.
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/helloworld']
images:
  - 'gcr.io/$PROJECT_ID/helloworld'
options:
  volumes:
    - name: go-modules
      path: /go